unit base;

interface

uses
  System.SysUtils, System.Classes, Data.DB, Data.Win.ADODB;

type
  TDataModule2 = class(TDataModule)
    ADOCommand1: TADOCommand;
    ADOTable1: TADOTable;
    ADOTable2: TADOTable;
    DataSource1: TDataSource;
    DataSource2: TDataSource;
    ADOQuery1: TADOQuery;
    DataSource3: TDataSource;
    ADOTable3: TADOTable;
    DataSource4: TDataSource;
    ADOTable4: TADOTable;
    DataSource5: TDataSource;
    DataSource6: TDataSource;
    ADOTable5: TADOTable;
    ADOQuery2: TADOQuery;
    DataSource7: TDataSource;
    ADOTable6: TADOTable;
    DataSource8: TDataSource;
    ADOConnection1: TADOConnection;
    DataSource9: TDataSource;
    ADOQuery4: TADOQuery;
    DataSource10: TDataSource;
    DataSource11: TDataSource;
    ADOTable7: TADOTable;
    ecolage: TDataSource;
    ADOQuery6: TADOQuery;
    reqecolage: TDataSource;
    DataSource12: TDataSource;
    ADOTable8: TADOTable;
    DataSource13: TDataSource;
    ADOTable9: TADOTable;
    DataSource14: TDataSource;
    ADOTable10: TADOTable;
    ADOTable10Matiere: TWideStringField;
    ADOTable10Trimestre: TWideStringField;
    ADOTable10Devoir: TIntegerField;
    ADOTable10Examen: TIntegerField;
    ADOTable10Observation: TWideStringField;
    ADOTable10NMatricule: TIntegerField;
    ADOTable9Trimestre: TWideStringField;
    ADOTable9Debut: TDateTimeField;
    ADOTable9Fin: TDateTimeField;
    ADOQuery7: TADOQuery;
    DataSource15: TDataSource;
    ADOQuery8: TADOQuery;
    ReqTrim: TDataSource;
    ADOQuery9: TADOQuery;
    reqecolage1: TDataSource;
    ADOTable11: TADOTable;
    DataSource16: TDataSource;
    ADOTable12: TADOTable;
    DataSource17: TDataSource;
    ADOTable13: TADOTable;
    DataSource18: TDataSource;
    ADOTable11Classe: TWideStringField;
    ADOTable11Prof: TWideStringField;
    ADOTable11Matiere: TWideStringField;
    ADOTable11Jours: TWideStringField;
    ADOTable11Duree: TIntegerField;
    ADOTable11Date: TDateTimeField;
    ADOQuery10: TADOQuery;
    DataSource19: TDataSource;
    ADOQuery5: TADOQuery;
    DataSource20: TDataSource;
    ADOTable14: TADOTable;
    ADOQuery11: TADOQuery;
    DataSource21: TDataSource;
    ADOTable15: TADOTable;
    DataSource22: TDataSource;
    ADOQuery12: TADOQuery;
    DataSource23: TDataSource;
    ADOQuery14: TADOQuery;
    DataSource25: TDataSource;
    ADOQuery14NMatricule: TIntegerField;
    ADOQuery14Responsable: TWideStringField;
    ADOQuery14Du: TDateTimeField;
    ADOQuery14Ecolagemois: TSmallintField;
    ADOQuery14SOMME: TIntegerField;
    ADOQuery1Classe: TWideStringField;
    ADOQuery1Tutilaire: TWideStringField;
    ADOQuery1Ecolage: TIntegerField;
    ADOQuery5Classe: TWideStringField;
    ADOQuery8Trimestre: TWideStringField;
    ADOQuery8ATO: TFloatField;
    ADOQuery2nb: TIntegerField;
    ADOQuery2Diplome: TWideStringField;
    ADOQuery4ecole: TIntegerField;
    ADOQuery6Classe: TWideStringField;
    DataSource26: TDataSource;
    ADOQuery16: TADOQuery;
    DataSource28: TDataSource;
    ADOQuery16USER: TWideStringField;
    ADOTable1Code: TWideStringField;
    ADOTable1Nom: TWideStringField;
    ADOTable1STAT: TWideStringField;
    ADOTable1NIF: TWideStringField;
    ADOTable1Adress: TWideStringField;
    ADOTable1email: TWideMemoField;
    ADOTable1Contact: TWideStringField;
    ADOTable4Appellation: TWideStringField;
    ADOTable4Nom: TWideStringField;
    ADOTable4Prenom: TWideStringField;
    ADOTable4Date_naissance: TDateTimeField;
    ADOTable4Lieu_naissance: TWideStringField;
    ADOTable4Adress: TWideStringField;
    ADOTable4NCIN: TWideStringField;
    ADOTable4Diplome: TWideStringField;
    ADOTable4Matiere: TWideStringField;
    ADOTable4Contact: TWideStringField;
    ADOTable4D_Classe: TWideStringField;
    ADOTable4F_Classe: TWideStringField;
    ADOTable4Salaire: TFloatField;
    ADOTable3Code: TWideStringField;
    ADOTable3Matiere: TWideStringField;
    ADOTable3Classe: TWideStringField;
    ADOTable3Serie: TWideStringField;
    ADOTable3Coefficient: TIntegerField;
    ADOTable6NMatricule: TAutoIncField;
    ADOTable6Nom: TWideStringField;
    ADOTable6Date_naissance: TDateTimeField;
    ADOTable6Lieu_naissance: TWideStringField;
    ADOTable6Fille_Fils: TWideStringField;
    ADOTable6Adresse: TWideStringField;
    ADOTable6Classe: TWideStringField;
    ADOTable6Contact: TWideStringField;
    ADOTable6Sexe: TWideStringField;
    ADOTable8id_ResF: TWideStringField;
    ADOTable8CIN: TWideStringField;
    ADOTable8Nom: TWideStringField;
    ADOTable8Adresse: TWideStringField;
    ADOTable8Telephone: TWideStringField;
    ADOTable8Mot_de_passe: TWideStringField;
    ADOTable8photo: TBlobField;
    ADOTable13NMatricule: TAutoIncField;
    ADOTable13Nom: TWideStringField;
    ADOTable13Date_naissance: TDateTimeField;
    ADOTable13Lieu_naissance: TWideStringField;
    ADOTable13Fille_Fils: TWideStringField;
    ADOTable13Adresse: TWideStringField;
    ADOTable13Classe: TWideStringField;
    ADOTable13Contact: TWideStringField;
    ADOTable13Sexe: TWideStringField;
    ADOTable14NMatricule: TAutoIncField;
    ADOTable14Nom: TWideStringField;
    ADOTable14Date_naissance: TDateTimeField;
    ADOTable14Lieu_naissance: TWideStringField;
    ADOTable14Fille_Fils: TWideStringField;
    ADOTable14Adresse: TWideStringField;
    ADOTable14Classe: TWideStringField;
    ADOTable14Contact: TWideStringField;
    ADOTable14Sexe: TWideStringField;
    ADOTable12Code: TWideStringField;
    ADOTable12Matiere: TWideStringField;
    ADOTable12Classe: TWideStringField;
    ADOTable12Serie: TWideStringField;
    ADOTable12Coefficient: TIntegerField;
    ADOQuery10Classe: TWideStringField;
    DataSource30: TDataSource;
    ADOTable17: TADOTable;
    DataSource31: TDataSource;
    ADOTable18: TADOTable;
    DataSource32: TDataSource;
    ADOTable18Matiere: TWideStringField;
    ADOTable18Trimestre: TWideStringField;
    ADOTable18Devoir: TIntegerField;
    ADOTable18Examen: TIntegerField;
    ADOTable18Observation: TWideStringField;
    ADOTable18NMatricule: TIntegerField;
    ADOQuery3: TADOQuery;
    ADOQuery3Classe: TWideStringField;
    ADOQuery3nombre: TIntegerField;
    ADOTable17NMatricule: TAutoIncField;
    ADOTable17Nom: TWideStringField;
    ADOTable17Date_naissance: TDateTimeField;
    ADOTable17Lieu_naissance: TWideStringField;
    ADOTable17Fille_Fils: TWideStringField;
    ADOTable17Adresse: TWideStringField;
    ADOTable17Classe: TWideStringField;
    ADOTable17Contact: TWideStringField;
    ADOTable17Sexe: TWideStringField;
    ADOQuery7Trimestre: TWideStringField;
    ADOQuery7Durée: TWideStringField;
    ADOQuery15: TADOQuery;
    ADOTable16: TADOTable;
    DataSource27: TDataSource;
    DataSource29: TDataSource;
    ADOTable19: TADOTable;
    ADOTable19id_ResF: TWideStringField;
    ADOTable19CIN: TWideStringField;
    ADOTable19Nom: TWideStringField;
    ADOTable19Adresse: TWideStringField;
    ADOTable19Telephone: TWideStringField;
    ADOTable19Mot_de_passe: TWideStringField;
    ADOTable19photo: TBlobField;
    SourceDataSet: TDataSource;
    ADODataSet2: TADODataSet;
    DataSource34: TDataSource;
    ADODataSet3: TADODataSet;
    DataSource35: TDataSource;
    ADOTable20: TADOTable;
    ADOTable20Classe: TWideStringField;
    ADOTable20Tutilaire: TWideStringField;
    ADOTable20Ecolage: TWideStringField;
    ADOTable2Classe: TWideStringField;
    ADOTable2Tutilaire: TWideStringField;
    ADOTable2Ecolage: TIntegerField;
    ADOTable5Classe: TWideStringField;
    ADOTable5Tutilaire: TWideStringField;
    ADOTable5Ecolage: TIntegerField;
    ADOTable15id_ResF: TWideStringField;
    ADOTable15CIN: TWideStringField;
    ADOTable15Nom: TWideStringField;
    ADOTable15Adresse: TWideStringField;
    ADOTable15Telephone: TWideStringField;
    ADOTable15code: TWideStringField;
    ADOTable15photo: TBlobField;
    ADODataSet1: TADODataSet;
    ADODataSet1id_ResF: TWideStringField;
    ADODataSet1code: TWideStringField;
    ADODataSet4: TADODataSet;
    ADODataSet2Ecolage_mois: TDateTimeField;
    ADODataSet3Ecolage_mois: TDateTimeField;
    ADOTable7NMatricule: TIntegerField;
    ADOTable7Ecolage_mois: TDateTimeField;
    ADOTable7Montant: TIntegerField;
    ADOTable7Date_payer: TDateTimeField;
    ADOTable7Responsable: TWideStringField;
    ADOTable7Mode_payement: TWideStringField;
    ADOTable7reglement: TBooleanField;
    ADOQuery9NMatricule: TIntegerField;
    ADOQuery9Ecolage_mois: TDateTimeField;
    ADOQuery9Date_payer: TDateTimeField;
    ADOQuery9Montant: TIntegerField;
    ADOQuery9Responsable: TWideStringField;
    procedure DataModuleCreate(Sender: TObject);
  private
    { Déclarations privées }
  public
    { Déclarations publiques }
  end;

var
  DataModule2: TDataModule2;

implementation

{%CLASSGROUP 'Vcl.Controls.TControl'}

{$R *.dfm}

procedure TDataModule2.DataModuleCreate(Sender: TObject);
begin
ADOConnection1.Close;
Adoconnection1.ConnectionString:= 'Provider=Microsoft.Jet.OLEDB.4.0;Data Source='+ExtractFilePath('application.ExecName')+'GesCo.mdb;Persist Security Info=False';
ADOConnection1.Open;
AdoDataset1.Active:=true;
AdoDataset2.Active:=true;
AdoDataset3.Active:=true;
AdoTable1.Active:=true;
AdoTable2.Active:=true;
AdoTable3.Active:=true;
AdoTable4.Active:=true;
AdoTable5.Active:=true;
AdoTable7.Active:=true;
AdoTable9.Active:=true;
AdoTable10.Active:=true;
AdoTable11.Active:=true;
AdoTable12.Active:=true;
AdoTable13.Active:=true;
AdoTable14.Active:=true;
AdoTable16.Active:=true;
AdoTable17.Active:=true;
AdoTable18.Active:=true;
AdoTable19.Active:=true;
AdoQuery1.Active:=true;
AdoQuery2.Active:=true;
AdoQuery4.Active:=true;
AdoQuery6.Active:=true;
AdoQuery7.Active:=true;
Adoquery9.Active:=true;
AdoQuery8.Active:=true;
AdoQuery10.Active:=true;
AdoQuery11.Active:=true;
AdoQuery12.Active:=true;
AdoQuery14.Active:=true;
AdoQuery15.Active:=true;
AdoQuery16.Active:=true;
AdoTable20.Active:=true;
end;

end.
